# yaml-language-server: $schema=https://render.com/schema/render.yaml.json
services:
  - type: web
    name: arama-api
    runtime: docker
    plan: free
    region: frankfurt
    rootDir: backend
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /api/v1/health
    autoDeploy: true
